declare module '@hugeicons/core-free-icons' {
  import type { FC, SVGProps } from 'react'

  export type HugeIcon = FC<SVGProps<SVGSVGElement>>

  // 常用图标导出（按需添加）
  export const ArrowRight: HugeIcon
  export const ChevronRight: HugeIcon
  export const Laptop: HugeIcon
  export const Moon: HugeIcon
  export const Sun: HugeIcon
  export const Check: HugeIcon
  export const Copy: HugeIcon
  export const X: HugeIcon
  export const Menu: HugeIcon
  export const ChevronDown: HugeIcon
  export const ChevronUp: HugeIcon
  export const ChevronLeft: HugeIcon
  export const Search: HugeIcon
  export const Settings: HugeIcon
  export const User: HugeIcon
  export const Users: HugeIcon
  export const LogOut: HugeIcon
  export const Home: HugeIcon
  export const Folder: HugeIcon
  export const File: HugeIcon
  export const FileText: HugeIcon
  export const Image: HugeIcon
  export const Video: HugeIcon
  export const Music: HugeIcon
  export const Mail: HugeIcon
  export const Phone: HugeIcon
  export const MapPin: HugeIcon
  export const Bell: HugeIcon
  export const Lock: HugeIcon
  export const Unlock: HugeIcon
  export const Eye: HugeIcon
  export const EyeOff: HugeIcon
  export const Edit: HugeIcon
  export const Trash: HugeIcon
  export const Plus: HugeIcon
  export const Minus: HugeIcon
  export const CheckCircle: HugeIcon
  export const XCircle: HugeIcon
  export const AlertCircle: HugeIcon
  export const Info: HugeIcon
  export const HelpCircle: HugeIcon
  export const Database: HugeIcon
  export const Server: HugeIcon
  export const Cloud: HugeIcon
  export const Download: HugeIcon
  export const Upload: HugeIcon
  export const RefreshCw: HugeIcon
  export const RotateCcw: HugeIcon
  export const Clock: HugeIcon
  export const Calendar: HugeIcon
  export const DollarSign: HugeIcon
  export const CreditCard: HugeIcon
  export const TrendingUp: HugeIcon
  export const TrendingDown: HugeIcon
  export const BarChart: HugeIcon
  export const LineChart: HugeIcon
  export const PieChart: HugeIcon
  export const Activity: HugeIcon
  export const Zap: HugeIcon
  export const Globe: HugeIcon
  export const Link: HugeIcon
  export const ExternalLink: HugeIcon
  export const GitBranch: HugeIcon
  export const Key: HugeIcon
  export const Smartphone: HugeIcon
  export const Webhook: HugeIcon
  export const Send: HugeIcon
  export const MessageSquare: HugeIcon
  export const Heart: HugeIcon
  export const Star: HugeIcon
  export const ThumbsUp: HugeIcon
  export const ThumbsDown: HugeIcon
  export const Share: HugeIcon
  export const Filter: HugeIcon
  export const Sliders: HugeIcon
  export const Grid: HugeIcon
  export const List: HugeIcon
  export const Layout: HugeIcon
  export const Maximize: HugeIcon
  export const Minimize: HugeIcon
  export const Move: HugeIcon
  export const Bold: HugeIcon
  export const Italic: HugeIcon
  export const Underline: HugeIcon
  export const Code: HugeIcon
  export const Code2: HugeIcon
  export const Quote: HugeIcon
  export const List: HugeIcon
  export const ListOrdered: HugeIcon
  export const AlignLeft: HugeIcon
  export const AlignCenter: HugeIcon
  export const AlignRight: HugeIcon
  export const Indent: HugeIcon
  export const Outdent: HugeIcon
  export const Undo: HugeIcon
  export const Redo: HugeIcon
  export const Printer: HugeIcon
  export const Save: HugeIcon
  export const Load: HugeIcon
}
